# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d1d4b192fac9cea0f2d6bf1d77692087ee1394a5c3119d7aabf45fc0453aeda8a0ab2ad04eb20ccbefb087c02c446f1ef62eb93e725f7602910b2d3a88d339

test:
  secret_key_base: 1368eff9790aa4951fde996555873d13c427517860819d8e85d7b0407798a2d45921d9b2cfb0e606ad6b11a95b0943b7f51d7aed14a10a2ca2d217ec0d4f5c04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
